/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health check
         * @description Checks Redis and PostgreSQL connectivity. Returns 200 when both dependencies are reachable, 503 when either is degraded. Unauthenticated; monitored by Uptime Kuma (ADR-005).
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenAPI 3.0 specification
         * @description Returns the full OpenAPI 3.0 specification for the NexusFlow REST API as JSON. Unauthenticated. Used by swagger-ui and openapi-typescript code generation. Cached by CDN for up to one hour (Cache-Control: public, max-age=3600).
         */
        get: operations["getOpenAPISpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate and obtain a session token
         * @description Validates username and password against the stored bcrypt hash. On success returns a session token in both the response body and an HTTP-only Secure cookie. Token TTL is 24 hours (ADR-006).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invalidate the current session
         * @description Deletes the session token from Redis. Always returns 204 regardless of whether the token was already expired or absent. Requires authentication.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tasks visible to the caller
         * @description User role: returns only the caller's own tasks. Admin role: returns all tasks across all users. Optional ?status= query parameter filters results to tasks with that exact status value.
         */
        get: operations["listTasks"];
        put?: never;
        /**
         * Submit a new task for execution
         * @description Creates a task referencing an existing pipeline and enqueues it to the Redis Stream matching the supplied capability tags. The task transitions through submitted → queued atomically before the response is returned. The submitting user and Admin may cancel this task later.
         */
        post: operations["submitTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a task by ID with state history
         * @description Returns the task and its full state transition audit trail. Enforces ownership: non-Admin callers may only read tasks they submitted.
         */
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a non-terminal task
         * @description Cancels a task that has not yet reached a terminal state (completed, failed, cancelled). Only the submitting user or an Admin may cancel. For tasks currently running on a worker, a cancel flag is set in Redis with a 60-second TTL so the worker can detect it mid-execution.
         */
        post: operations["cancelTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve historical log lines for a task
         * @description Returns all cold-stored log lines for the task ordered by timestamp. Hot logs (0–72 h) are also available via the SSE stream GET /events/tasks/{id}/logs. Only the task owner or an Admin may retrieve logs.
         */
        get: operations["getTaskLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pipelines visible to the caller
         * @description User role: returns only the caller's own pipelines. Admin role: returns all pipelines across all users.
         */
        get: operations["listPipelines"];
        put?: never;
        /**
         * Create a new pipeline
         * @description Creates a pipeline with DataSource, Process, and Sink phase configurations. Schema mappings are validated at design time (TASK-026, ADR-008): all SourceFields in ProcessConfig.inputMappings must exist in DataSourceConfig.outputSchema, and all SourceFields in SinkConfig.inputMappings must exist in ProcessConfig.outputSchema.
         */
        post: operations["createPipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipelines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a pipeline by ID
         * @description Returns the full pipeline definition. Only the owner or an Admin may access it.
         */
        get: operations["getPipeline"];
        /**
         * Replace a pipeline's mutable fields
         * @description Full replacement of name and phase configurations. Schema mappings are re-validated on every update. Only the owner or an Admin may update.
         */
        put: operations["updatePipeline"];
        post?: never;
        /**
         * Delete a pipeline
         * @description Deletes the pipeline. Rejected with 409 if any non-terminal task references this pipeline. Only the owner or an Admin may delete.
         */
        delete: operations["deletePipeline"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipelines/{id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate pipeline schema mappings without persisting
         * @description Runs design-time schema mapping validation against the supplied pipeline definition without creating or updating any record. Returns 200 on a valid mapping, 400 with the first validation error on failure.
         */
        post: operations["validatePipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all registered workers
         * @description Returns all workers in the registry regardless of status (online or down). Available to all authenticated users — both User and Admin role.
         */
        get: operations["listWorkers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a pipeline chain
         * @description Creates a strictly linear sequence of pipelines (A → B → C). Completion of each pipeline triggers the next. Failure in any pipeline cascades cancellation to all downstream pipelines. Branching structures (duplicate pipeline IDs) are rejected. Requires at least two pipelines.
         */
        post: operations["createChain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a chain by ID
         * @description Returns the chain definition with its ordered pipeline list.
         */
        get: operations["getChain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all user accounts (admin only)
         * @description Returns all user accounts ordered by creation time. Admin role required.
         */
        get: operations["listUsers"];
        put?: never;
        /**
         * Create a user account (admin only)
         * @description Creates a new user account. The password is bcrypt-hashed at cost 12. Admin role required — enforced by RequireRole middleware.
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Deactivate a user account (admin only)
         * @description Sets the user's active flag to false and invalidates all of the user's active Redis sessions. Does not cancel in-flight tasks. Admin role required.
         */
        put: operations["deactivateUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @description Overall service status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * @description Redis connectivity result
             * @enum {string}
             */
            redis: "ok" | "error";
            /**
             * @description PostgreSQL connectivity result
             * @enum {string}
             */
            postgres: "ok" | "error";
        };
        ErrorResponse: {
            /** @description Human-readable error message */
            error: string;
        };
        /**
         * @description Task lifecycle state. Transitions are monotonically forward except for assigned/running → queued on infrastructure failover.
         * @enum {string}
         */
        TaskStatus: "submitted" | "queued" | "assigned" | "running" | "completed" | "failed" | "cancelled";
        /**
         * @description Retry delay growth strategy between task execution attempts
         * @enum {string}
         */
        BackoffStrategy: "exponential" | "linear" | "fixed";
        RetryConfig: {
            /** @description Maximum number of retry attempts. Default is 3. */
            maxRetries: number;
            backoff: components["schemas"]["BackoffStrategy"];
        };
        SchemaMapping: {
            /** @description Field name in the preceding phase's output schema */
            sourceField: string;
            /** @description Field name expected by the next phase's input schema */
            targetField: string;
        };
        DataSourceConfig: {
            /** @description DataSource connector identifier (e.g. "demo", "s3", "postgres") */
            connectorType: string;
            /** @description Connector-specific configuration parameters */
            config: {
                [key: string]: unknown;
            };
            /** @description Field names this phase produces; used for schema mapping validation */
            outputSchema: string[];
        };
        ProcessConfig: {
            /** @description Process connector identifier */
            connectorType: string;
            /** @description Connector-specific configuration parameters */
            config: {
                [key: string]: unknown;
            };
            /** @description Maps DataSource output fields to Process input fields. All sourceField values must exist in DataSourceConfig.outputSchema. */
            inputMappings: components["schemas"]["SchemaMapping"][];
            /** @description Field names this phase produces */
            outputSchema: string[];
        };
        SinkConfig: {
            /** @description Sink connector identifier (e.g. "demo", "s3", "postgres") */
            connectorType: string;
            /** @description Connector-specific configuration parameters */
            config: {
                [key: string]: unknown;
            };
            /** @description Maps Process output fields to Sink input fields. All sourceField values must exist in ProcessConfig.outputSchema. */
            inputMappings: components["schemas"]["SchemaMapping"][];
        };
        LoginRequest: {
            /** @description Account username */
            username: string;
            /**
             * Format: password
             * @description Account password (plaintext; transmitted over HTTPS only)
             */
            password: string;
        };
        LoginResponse: {
            /** @description Session token for use in Authorization: Bearer header */
            token: string;
            user: components["schemas"]["PublicUser"];
        };
        PublicUser: {
            /** Format: uuid */
            id: string;
            username: string;
            role: components["schemas"]["Role"];
        };
        /**
         * @description User access level. admin has full visibility; user sees own resources only.
         * @enum {string}
         */
        Role: "admin" | "user";
        SubmitTaskRequest: {
            /**
             * Format: uuid
             * @description UUID of the pipeline to execute. Must exist in the database.
             */
            pipelineId: string;
            /** @description Arbitrary key-value runtime parameters passed to the pipeline */
            input?: {
                [key: string]: unknown;
            };
            /** @description Capability tags used to route the task to a matching worker */
            tags: string[];
            retryConfig?: components["schemas"]["RetryConfig"];
        };
        SubmitTaskResponse: {
            /**
             * Format: uuid
             * @description UUID of the newly created task
             */
            taskId: string;
            status: components["schemas"]["TaskStatus"];
        };
        Task: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Pipeline UUID; null when the referenced pipeline has been deleted
             */
            pipelineId?: string | null;
            /**
             * Format: uuid
             * @description Chain UUID if this task is part of a pipeline chain
             */
            chainId?: string | null;
            /**
             * Format: uuid
             * @description UUID of the user who submitted this task
             */
            userId: string;
            status: components["schemas"]["TaskStatus"];
            retryConfig: components["schemas"]["RetryConfig"];
            /** @description Number of times this task has been retried */
            retryCount: number;
            /**
             * Format: date-time
             * @description When set, the task must not be re-enqueued until this timestamp elapses. Null when the task has never been retried or is immediately ready.
             */
            retryAfter?: string | null;
            /** @description Capability tag streams to re-enqueue the task to on retry */
            retryTags?: string[];
            /** @description task-id:attempt-number encoding for Sink idempotency (ADR-003) */
            executionId: string;
            /** @description ID of the worker currently executing this task; null when unassigned */
            workerId?: string | null;
            /** @description Runtime parameters passed to the pipeline */
            input: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TaskStateLog: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            taskId: string;
            fromState: components["schemas"]["TaskStatus"];
            toState: components["schemas"]["TaskStatus"];
            /** @description Human-readable reason for the state transition */
            reason: string;
            /** Format: date-time */
            timestamp: string;
        };
        TaskDetailResponse: {
            task: components["schemas"]["Task"];
            /** @description Chronological list of all state transitions for this task */
            stateHistory: components["schemas"]["TaskStateLog"][];
        };
        TaskLog: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            taskId: string;
            /** @description Log message text */
            line: string;
            /** @description Log level (e.g. "info", "warn", "error") */
            level: string;
            /** Format: date-time */
            timestamp: string;
        };
        Pipeline: {
            /** Format: uuid */
            id: string;
            /** @description Human-readable pipeline name */
            name: string;
            /**
             * Format: uuid
             * @description UUID of the user who created this pipeline
             */
            userId: string;
            dataSourceConfig: components["schemas"]["DataSourceConfig"];
            processConfig: components["schemas"]["ProcessConfig"];
            sinkConfig: components["schemas"]["SinkConfig"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreatePipelineRequest: {
            /** @description Human-readable pipeline name. Must be non-empty. */
            name: string;
            dataSourceConfig: components["schemas"]["DataSourceConfig"];
            processConfig: components["schemas"]["ProcessConfig"];
            sinkConfig: components["schemas"]["SinkConfig"];
        };
        UpdatePipelineRequest: {
            name: string;
            dataSourceConfig: components["schemas"]["DataSourceConfig"];
            processConfig: components["schemas"]["ProcessConfig"];
            sinkConfig: components["schemas"]["SinkConfig"];
        };
        Chain: {
            /** Format: uuid */
            id: string;
            /** @description Human-readable chain name */
            name: string;
            /**
             * Format: uuid
             * @description UUID of the user who created this chain
             */
            userId: string;
            /** @description Ordered list of pipeline UUIDs forming the chain (index 0 executes first) */
            pipelineIds: string[];
            /** Format: date-time */
            createdAt: string;
        };
        CreateChainRequest: {
            /** @description Human-readable chain name. Must be non-empty. */
            name: string;
            /** @description Ordered list of pipeline UUIDs forming the chain. Must have at least two entries. Duplicate entries are rejected (would constitute branching). */
            pipelineIds: string[];
        };
        Worker: {
            /** @description Worker identifier (self-assigned on startup, e.g. hostname:pid) */
            id: string;
            /** @description Capability tags that determine which task queues this worker consumes */
            tags: string[];
            /**
             * @description online = recently heartbeated; down = heartbeat overdue
             * @enum {string}
             */
            status: "online" | "down";
            /**
             * Format: date-time
             * @description Timestamp of the most recent heartbeat received from this worker
             */
            lastHeartbeat: string;
            /**
             * Format: date-time
             * @description Timestamp when this worker first registered
             */
            registeredAt: string;
            /**
             * Format: uuid
             * @description UUID of the task currently being executed; null when idle
             */
            currentTaskId?: string | null;
        };
        CreateUserRequest: {
            /** @description Account username. Must be unique. */
            username: string;
            /**
             * Format: password
             * @description Account password (plaintext; bcrypt-hashed at cost 12 before storage)
             */
            password: string;
            role: components["schemas"]["Role"];
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            username: string;
            role: components["schemas"]["Role"];
            /** @description false after deactivation */
            active: boolean;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: {
        /** @description No valid session token present */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Caller does not own the resource and is not Admin */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Task UUID */
        TaskId: string;
        /** @description Pipeline UUID */
        PipelineId: string;
        /** @description Chain UUID */
        ChainId: string;
        /** @description User UUID */
        UserId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All dependencies reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "redis": "ok",
                     *       "postgres": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description One or more dependencies unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "degraded",
                     *       "redis": "error",
                     *       "postgres": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getOpenAPISpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI 3.0 JSON specification */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    /** @description session=<token>; HttpOnly; Secure; SameSite=Strict; Max-Age=86400 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Malformed JSON body or empty username/password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid credentials or deactivated account */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session invalidated (or was already absent) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No token present in the request */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listTasks: {
        parameters: {
            query?: {
                /** @description Filter by task status */
                status?: components["schemas"]["TaskStatus"];
                /** @description Filter by pipeline UUID */
                pipelineId?: string;
                /** @description Free-text search against task metadata (client-side filter) */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of tasks (empty array when none match) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    submitTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitTaskRequest"];
            };
        };
        responses: {
            /** @description Task accepted and queued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitTaskResponse"];
                };
            };
            /** @description Malformed JSON, missing fields, invalid pipelineId, or pipeline not found */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task detail with state history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetailResponse"];
                };
            };
            /** @description id is not a valid UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    cancelTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task cancelled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description id is not a valid UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Task is already in a terminal state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getTaskLogs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of log lines (empty array when none exist) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskLog"][];
                };
            };
            /** @description id is not a valid UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listPipelines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of pipelines (empty array when none exist) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pipeline"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePipelineRequest"];
            };
        };
        responses: {
            /** @description Pipeline created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pipeline"];
                };
            };
            /** @description Malformed JSON, missing name, or invalid schema mapping */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pipeline UUID */
                id: components["parameters"]["PipelineId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pipeline detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pipeline"];
                };
            };
            /** @description id is not a valid UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updatePipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pipeline UUID */
                id: components["parameters"]["PipelineId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePipelineRequest"];
            };
        };
        responses: {
            /** @description Updated pipeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pipeline"];
                };
            };
            /** @description Malformed JSON, invalid id, or invalid schema mapping */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deletePipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pipeline UUID */
                id: components["parameters"]["PipelineId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pipeline deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description id is not a valid UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Pipeline has active (non-terminal) tasks */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    validatePipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pipeline UUID */
                id: components["parameters"]["PipelineId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePipelineRequest"];
            };
        };
        responses: {
            /** @description Schema mappings are valid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Schema mapping validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listWorkers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of workers (empty array when none are registered) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Worker"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createChain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChainRequest"];
            };
        };
        responses: {
            /** @description Chain created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chain"];
                };
            };
            /** @description Malformed JSON, missing name, fewer than 2 pipelines, duplicate pipeline IDs, or any pipelineId is not a valid UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getChain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chain UUID */
                id: components["parameters"]["ChainId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chain detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chain"];
                };
            };
            /** @description id is not a valid UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of user accounts (empty array when none exist) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Malformed JSON, empty username/password, or invalid role */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Username already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    deactivateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User UUID */
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deactivated and sessions invalidated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description id is not a valid UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
}
