// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chains.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChain = `-- name: CreateChain :one

INSERT INTO chains (id, name, user_id, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, user_id, created_at
`

type CreateChainParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// sqlc query file: chains and chain_steps tables
// Generates Go code in internal/db/sqlc/ via `sqlc generate`
// See: ADR-008, TASK-014, REQ-014
func (q *Queries) CreateChain(ctx context.Context, arg CreateChainParams) (Chain, error) {
	row := q.db.QueryRow(ctx, createChain,
		arg.ID,
		arg.Name,
		arg.UserID,
		arg.CreatedAt,
	)
	var i Chain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createChainStep = `-- name: CreateChainStep :exec
INSERT INTO chain_steps (chain_id, pipeline_id, position)
VALUES ($1, $2, $3)
`

type CreateChainStepParams struct {
	ChainID    uuid.UUID `db:"chain_id" json:"chain_id"`
	PipelineID uuid.UUID `db:"pipeline_id" json:"pipeline_id"`
	Position   int32     `db:"position" json:"position"`
}

func (q *Queries) CreateChainStep(ctx context.Context, arg CreateChainStepParams) error {
	_, err := q.db.Exec(ctx, createChainStep, arg.ChainID, arg.PipelineID, arg.Position)
	return err
}

const findChainByPipeline = `-- name: FindChainByPipeline :one
SELECT c.id, c.name, c.user_id, c.created_at FROM chains c
JOIN chain_steps cs ON cs.chain_id = c.id
WHERE cs.pipeline_id = $1
LIMIT 1
`

// Returns the chain containing the given pipeline_id, if any.
// Used by the chain trigger to determine whether a completed task's pipeline is in a chain.
func (q *Queries) FindChainByPipeline(ctx context.Context, pipelineID uuid.UUID) (Chain, error) {
	row := q.db.QueryRow(ctx, findChainByPipeline, pipelineID)
	var i Chain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getChainByID = `-- name: GetChainByID :one
SELECT id, name, user_id, created_at FROM chains WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChainByID(ctx context.Context, id uuid.UUID) (Chain, error) {
	row := q.db.QueryRow(ctx, getChainByID, id)
	var i Chain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getChainSteps = `-- name: GetChainSteps :many
SELECT chain_id, pipeline_id, position FROM chain_steps WHERE chain_id = $1 ORDER BY position ASC
`

// Returns all steps for a chain ordered by position (ascending).
func (q *Queries) GetChainSteps(ctx context.Context, chainID uuid.UUID) ([]ChainStep, error) {
	rows, err := q.db.Query(ctx, getChainSteps, chainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChainStep
	for rows.Next() {
		var i ChainStep
		if err := rows.Scan(&i.ChainID, &i.PipelineID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextPipelineInChain = `-- name: GetNextPipelineInChain :one
SELECT cs_next.pipeline_id
FROM chain_steps cs_current
JOIN chain_steps cs_next
  ON cs_next.chain_id = cs_current.chain_id
 AND cs_next.position = cs_current.position + 1
WHERE cs_current.chain_id    = $1
  AND cs_current.pipeline_id = $2
LIMIT 1
`

type GetNextPipelineInChainParams struct {
	ChainID    uuid.UUID `db:"chain_id" json:"chain_id"`
	PipelineID uuid.UUID `db:"pipeline_id" json:"pipeline_id"`
}

// Returns the pipeline_id of the step immediately after the given pipeline in the chain.
// Returns no rows when the given pipeline is the last step.
func (q *Queries) GetNextPipelineInChain(ctx context.Context, arg GetNextPipelineInChainParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getNextPipelineInChain, arg.ChainID, arg.PipelineID)
	var pipeline_id uuid.UUID
	err := row.Scan(&pipeline_id)
	return pipeline_id, err
}
