// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logs.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const batchInsertLogs = `-- name: BatchInsertLogs :exec

INSERT INTO task_logs (id, task_id, line, level, timestamp)
VALUES ($1, $2, $3, $4, $5)
`

type BatchInsertLogsParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	TaskID    uuid.UUID          `db:"task_id" json:"task_id"`
	Line      string             `db:"line" json:"line"`
	Level     string             `db:"level" json:"level"`
	Timestamp pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
}

// sqlc query file: task_logs table (cold log storage, partitioned by week)
// Generates Go code in internal/db/sqlc/ via `sqlc generate`
// See: ADR-008, TASK-002, TASK-016
// Inserts a single log line. Callers loop over slices; sqlc does not support
// bulk-insert with variable-length input directly.
func (q *Queries) BatchInsertLogs(ctx context.Context, arg BatchInsertLogsParams) error {
	_, err := q.db.Exec(ctx, batchInsertLogs,
		arg.ID,
		arg.TaskID,
		arg.Line,
		arg.Level,
		arg.Timestamp,
	)
	return err
}

const listLogsByTask = `-- name: ListLogsByTask :many
SELECT id, task_id, line, level, timestamp FROM task_logs
WHERE task_id = $1
  AND id > $2
ORDER BY timestamp ASC, id ASC
`

type ListLogsByTaskParams struct {
	TaskID uuid.UUID `db:"task_id" json:"task_id"`
	ID     uuid.UUID `db:"id" json:"id"`
}

// Returns log lines for a task ordered by timestamp.
// afterID filters for Last-Event-ID replay: only rows with id > afterID are returned.
// When afterID is the zero UUID ('00000000-0000-0000-0000-000000000000'), all rows are returned.
func (q *Queries) ListLogsByTask(ctx context.Context, arg ListLogsByTaskParams) ([]TaskLog, error) {
	rows, err := q.db.Query(ctx, listLogsByTask, arg.TaskID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskLog
	for rows.Next() {
		var i TaskLog
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Line,
			&i.Level,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
