// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Chain struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ChainStep struct {
	ChainID    uuid.UUID `db:"chain_id" json:"chain_id"`
	PipelineID uuid.UUID `db:"pipeline_id" json:"pipeline_id"`
	Position   int32     `db:"position" json:"position"`
}

type Pipeline struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	Name             string             `db:"name" json:"name"`
	UserID           uuid.UUID          `db:"user_id" json:"user_id"`
	DataSourceConfig json.RawMessage    `db:"data_source_config" json:"data_source_config"`
	ProcessConfig    json.RawMessage    `db:"process_config" json:"process_config"`
	SinkConfig       json.RawMessage    `db:"sink_config" json:"sink_config"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PipelineChain struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	PipelineIds []uuid.UUID        `db:"pipeline_ids" json:"pipeline_ids"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Records execution IDs that have been atomically committed at a Sink destination. Used to enforce idempotency: a second write attempt with the same execution_id is rejected before any rows are written. See ADR-003, ADR-009.
type SinkDedupLog struct {
	ExecutionID   string             `db:"execution_id" json:"execution_id"`
	ConnectorType string             `db:"connector_type" json:"connector_type"`
	AppliedAt     pgtype.Timestamptz `db:"applied_at" json:"applied_at"`
}

type Task struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	PipelineID  uuid.NullUUID      `db:"pipeline_id" json:"pipeline_id"`
	ChainID     uuid.NullUUID      `db:"chain_id" json:"chain_id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	Status      string             `db:"status" json:"status"`
	RetryConfig json.RawMessage    `db:"retry_config" json:"retry_config"`
	RetryCount  int32              `db:"retry_count" json:"retry_count"`
	RetryAfter  pgtype.Timestamptz `db:"retry_after" json:"retry_after"`
	RetryTags   []string           `db:"retry_tags" json:"retry_tags"`
	ExecutionID string             `db:"execution_id" json:"execution_id"`
	WorkerID    *string            `db:"worker_id" json:"worker_id"`
	Input       json.RawMessage    `db:"input" json:"input"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TaskLog struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	TaskID    uuid.UUID          `db:"task_id" json:"task_id"`
	Line      string             `db:"line" json:"line"`
	Level     string             `db:"level" json:"level"`
	Timestamp pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
}

type TaskLogsDefault struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	TaskID    uuid.UUID          `db:"task_id" json:"task_id"`
	Line      string             `db:"line" json:"line"`
	Level     string             `db:"level" json:"level"`
	Timestamp pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
}

type TaskStateLog struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	TaskID    uuid.UUID          `db:"task_id" json:"task_id"`
	FromState string             `db:"from_state" json:"from_state"`
	ToState   string             `db:"to_state" json:"to_state"`
	Reason    string             `db:"reason" json:"reason"`
	Timestamp pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
}

type User struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Username     string             `db:"username" json:"username"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	Role         string             `db:"role" json:"role"`
	Active       bool               `db:"active" json:"active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Worker struct {
	ID            string             `db:"id" json:"id"`
	Tags          []string           `db:"tags" json:"tags"`
	Status        string             `db:"status" json:"status"`
	LastHeartbeat pgtype.Timestamptz `db:"last_heartbeat" json:"last_heartbeat"`
	RegisteredAt  pgtype.Timestamptz `db:"registered_at" json:"registered_at"`
}
