// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipelines.sql

package sqlcdb

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPipeline = `-- name: CreatePipeline :one

INSERT INTO pipelines (id, name, user_id, data_source_config, process_config, sink_config, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, user_id, data_source_config, process_config, sink_config, created_at, updated_at
`

type CreatePipelineParams struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	Name             string             `db:"name" json:"name"`
	UserID           uuid.UUID          `db:"user_id" json:"user_id"`
	DataSourceConfig json.RawMessage    `db:"data_source_config" json:"data_source_config"`
	ProcessConfig    json.RawMessage    `db:"process_config" json:"process_config"`
	SinkConfig       json.RawMessage    `db:"sink_config" json:"sink_config"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// sqlc query file: pipelines and pipeline_chains tables
// Generates Go code in internal/db/sqlc/ via `sqlc generate`
// See: ADR-008, TASK-002, TASK-013, TASK-014
func (q *Queries) CreatePipeline(ctx context.Context, arg CreatePipelineParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, createPipeline,
		arg.ID,
		arg.Name,
		arg.UserID,
		arg.DataSourceConfig,
		arg.ProcessConfig,
		arg.SinkConfig,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.DataSourceConfig,
		&i.ProcessConfig,
		&i.SinkConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePipeline = `-- name: DeletePipeline :exec
DELETE FROM pipelines WHERE id = $1
`

func (q *Queries) DeletePipeline(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePipeline, id)
	return err
}

const getPipelineByID = `-- name: GetPipelineByID :one
SELECT id, name, user_id, data_source_config, process_config, sink_config, created_at, updated_at FROM pipelines WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPipelineByID(ctx context.Context, id uuid.UUID) (Pipeline, error) {
	row := q.db.QueryRow(ctx, getPipelineByID, id)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.DataSourceConfig,
		&i.ProcessConfig,
		&i.SinkConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPipelines = `-- name: ListAllPipelines :many
SELECT id, name, user_id, data_source_config, process_config, sink_config, created_at, updated_at FROM pipelines ORDER BY created_at ASC
`

func (q *Queries) ListAllPipelines(ctx context.Context) ([]Pipeline, error) {
	rows, err := q.db.Query(ctx, listAllPipelines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pipeline
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.DataSourceConfig,
			&i.ProcessConfig,
			&i.SinkConfig,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelinesByUser = `-- name: ListPipelinesByUser :many
SELECT id, name, user_id, data_source_config, process_config, sink_config, created_at, updated_at FROM pipelines WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListPipelinesByUser(ctx context.Context, userID uuid.UUID) ([]Pipeline, error) {
	rows, err := q.db.Query(ctx, listPipelinesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pipeline
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.DataSourceConfig,
			&i.ProcessConfig,
			&i.SinkConfig,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pipelineHasActiveTasks = `-- name: PipelineHasActiveTasks :one
SELECT EXISTS (
    SELECT 1 FROM tasks
    WHERE pipeline_id = $1
      AND status NOT IN ('completed', 'failed', 'cancelled')
) AS has_active_tasks
`

// Returns TRUE if any non-terminal task references this pipeline.
func (q *Queries) PipelineHasActiveTasks(ctx context.Context, pipelineID uuid.NullUUID) (bool, error) {
	row := q.db.QueryRow(ctx, pipelineHasActiveTasks, pipelineID)
	var has_active_tasks bool
	err := row.Scan(&has_active_tasks)
	return has_active_tasks, err
}

const updatePipeline = `-- name: UpdatePipeline :one
UPDATE pipelines
SET name               = $2,
    data_source_config = $3,
    process_config     = $4,
    sink_config        = $5,
    updated_at         = $6
WHERE id = $1
RETURNING id, name, user_id, data_source_config, process_config, sink_config, created_at, updated_at
`

type UpdatePipelineParams struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	Name             string             `db:"name" json:"name"`
	DataSourceConfig json.RawMessage    `db:"data_source_config" json:"data_source_config"`
	ProcessConfig    json.RawMessage    `db:"process_config" json:"process_config"`
	SinkConfig       json.RawMessage    `db:"sink_config" json:"sink_config"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdatePipeline(ctx context.Context, arg UpdatePipelineParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, updatePipeline,
		arg.ID,
		arg.Name,
		arg.DataSourceConfig,
		arg.ProcessConfig,
		arg.SinkConfig,
		arg.UpdatedAt,
	)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.DataSourceConfig,
		&i.ProcessConfig,
		&i.SinkConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
