// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlcdb

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelTask = `-- name: CancelTask :exec
UPDATE tasks
SET status     = 'cancelled',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CancelTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelTask, id)
	return err
}

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (id, pipeline_id, chain_id, user_id, status, retry_config, retry_count, execution_id, worker_id, input, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, pipeline_id, chain_id, user_id, status, retry_config, retry_count, execution_id, worker_id, input, created_at, updated_at
`

type CreateTaskParams struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	PipelineID  uuid.NullUUID      `db:"pipeline_id" json:"pipeline_id"`
	ChainID     uuid.NullUUID      `db:"chain_id" json:"chain_id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	Status      string             `db:"status" json:"status"`
	RetryConfig json.RawMessage    `db:"retry_config" json:"retry_config"`
	RetryCount  int32              `db:"retry_count" json:"retry_count"`
	ExecutionID string             `db:"execution_id" json:"execution_id"`
	WorkerID    *string            `db:"worker_id" json:"worker_id"`
	Input       json.RawMessage    `db:"input" json:"input"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// sqlc query file: tasks and task_state_log tables
// Generates Go code in internal/db/sqlc/ via `sqlc generate`
// See: ADR-008, TASK-002, TASK-005, TASK-007
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.PipelineID,
		arg.ChainID,
		arg.UserID,
		arg.Status,
		arg.RetryConfig,
		arg.RetryCount,
		arg.ExecutionID,
		arg.WorkerID,
		arg.Input,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.ChainID,
		&i.UserID,
		&i.Status,
		&i.RetryConfig,
		&i.RetryCount,
		&i.ExecutionID,
		&i.WorkerID,
		&i.Input,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, pipeline_id, chain_id, user_id, status, retry_config, retry_count, execution_id, worker_id, input, created_at, updated_at FROM tasks WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.ChainID,
		&i.UserID,
		&i.Status,
		&i.RetryConfig,
		&i.RetryCount,
		&i.ExecutionID,
		&i.WorkerID,
		&i.Input,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskStateLog = `-- name: GetTaskStateLog :many
SELECT id, task_id, from_state, to_state, reason, timestamp FROM task_state_log WHERE task_id = $1 ORDER BY timestamp ASC
`

func (q *Queries) GetTaskStateLog(ctx context.Context, taskID uuid.UUID) ([]TaskStateLog, error) {
	rows, err := q.db.Query(ctx, getTaskStateLog, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskStateLog
	for rows.Next() {
		var i TaskStateLog
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.FromState,
			&i.ToState,
			&i.Reason,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementTaskRetryCount = `-- name: IncrementTaskRetryCount :one
UPDATE tasks
SET retry_count = retry_count + 1,
    updated_at  = NOW()
WHERE id = $1
RETURNING retry_count
`

func (q *Queries) IncrementTaskRetryCount(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementTaskRetryCount, id)
	var retry_count int32
	err := row.Scan(&retry_count)
	return retry_count, err
}

const insertTaskStateLog = `-- name: InsertTaskStateLog :exec
INSERT INTO task_state_log (id, task_id, from_state, to_state, reason, timestamp)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTaskStateLogParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	TaskID    uuid.UUID          `db:"task_id" json:"task_id"`
	FromState string             `db:"from_state" json:"from_state"`
	ToState   string             `db:"to_state" json:"to_state"`
	Reason    string             `db:"reason" json:"reason"`
	Timestamp pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
}

func (q *Queries) InsertTaskStateLog(ctx context.Context, arg InsertTaskStateLogParams) error {
	_, err := q.db.Exec(ctx, insertTaskStateLog,
		arg.ID,
		arg.TaskID,
		arg.FromState,
		arg.ToState,
		arg.Reason,
		arg.Timestamp,
	)
	return err
}

const listAllTasks = `-- name: ListAllTasks :many
SELECT id, pipeline_id, chain_id, user_id, status, retry_config, retry_count, execution_id, worker_id, input, created_at, updated_at FROM tasks ORDER BY created_at DESC
`

func (q *Queries) ListAllTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.ChainID,
			&i.UserID,
			&i.Status,
			&i.RetryConfig,
			&i.RetryCount,
			&i.ExecutionID,
			&i.WorkerID,
			&i.Input,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByUser = `-- name: ListTasksByUser :many
SELECT id, pipeline_id, chain_id, user_id, status, retry_config, retry_count, execution_id, worker_id, input, created_at, updated_at FROM tasks WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTasksByUser(ctx context.Context, userID uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.ChainID,
			&i.UserID,
			&i.Status,
			&i.RetryConfig,
			&i.RetryCount,
			&i.ExecutionID,
			&i.WorkerID,
			&i.Input,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks
SET status     = $2,
    worker_id  = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateTaskStatusParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Status   string    `db:"status" json:"status"`
	WorkerID *string   `db:"worker_id" json:"worker_id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.ID, arg.Status, arg.WorkerID)
	return err
}
