// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql
//
// NOTE (SEC-001 scaffold): This file was manually updated to add must_change_password
// to all SELECT column lists and Scan calls, and to add UpdateUserPassword, to match
// migration 000007. The Builder must run `sqlc generate` after applying migration 000007
// to regenerate this file from the canonical query definitions. The manual edits here
// will be overwritten by sqlc generate.

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, username, password_hash, role, active, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, password_hash, role, active, must_change_password, created_at
`

type CreateUserParams struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	Username     string             `db:"username" json:"username"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	Role         string             `db:"role" json:"role"`
	Active       bool               `db:"active" json:"active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// sqlc query file: users table
// Generates Go code in internal/db/sqlc/ via `sqlc generate`
// See: ADR-008, TASK-002, TASK-017, SEC-001
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.Active,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.MustChangePassword,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET active = FALSE WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, role, active, must_change_password, created_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.MustChangePassword,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, active, must_change_password, created_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.MustChangePassword,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, role, active, must_change_password, created_at FROM users ORDER BY created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.Active,
			&i.MustChangePassword,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
-- SEC-001: update password_hash and clear must_change_password in one atomic statement.
UPDATE users
SET password_hash = $2, must_change_password = FALSE
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
}

// UpdateUserPassword updates the user's password hash and clears the must_change_password flag.
// Called by PasswordChangeHandler after verifying the current password (SEC-001).
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	// TODO: implement — will be generated correctly after `sqlc generate` is run
	// against migration 000007. This stub exists so the package compiles.
	panic("not implemented — run sqlc generate after applying migration 000007")
}
