// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, username, password_hash, role, active, must_change_password, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, username, password_hash, role, active, created_at, must_change_password
`

type CreateUserParams struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	Username           string             `db:"username" json:"username"`
	PasswordHash       string             `db:"password_hash" json:"password_hash"`
	Role               string             `db:"role" json:"role"`
	Active             bool               `db:"active" json:"active"`
	MustChangePassword bool               `db:"must_change_password" json:"must_change_password"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// sqlc query file: users table
// Generates Go code in internal/db/sqlc/ via `sqlc generate`
// See: ADR-008, TASK-002, TASK-017
// SEC-001: must_change_password is included so seed and admin-created users can be
// flagged for forced rotation on first login.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.Active,
		arg.MustChangePassword,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.MustChangePassword,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET active = FALSE WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, role, active, created_at, must_change_password FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.MustChangePassword,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, active, created_at, must_change_password FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.MustChangePassword,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, role, active, created_at, must_change_password FROM users ORDER BY created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.Active,
			&i.CreatedAt,
			&i.MustChangePassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, must_change_password = FALSE
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
}

// SEC-001: update password_hash and clear must_change_password in one atomic statement.
// Called by PasswordChangeHandler after verifying the current password.
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
