// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workers.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getWorkerByID = `-- name: GetWorkerByID :one
SELECT id, tags, status, last_heartbeat, registered_at FROM workers WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorkerByID(ctx context.Context, id string) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByID, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Tags,
		&i.Status,
		&i.LastHeartbeat,
		&i.RegisteredAt,
	)
	return i, err
}

const listWorkers = `-- name: ListWorkers :many
SELECT
    w.id,
    w.tags,
    w.status,
    w.last_heartbeat,
    w.registered_at,
    (
        SELECT t.id
        FROM tasks t
        WHERE t.worker_id = w.id
          AND t.status IN ('assigned', 'running')
        ORDER BY t.updated_at DESC
        LIMIT 1
    ) AS current_task_id
FROM workers w
ORDER BY w.registered_at ASC
`

type ListWorkersRow struct {
	ID            string             `db:"id" json:"id"`
	Tags          []string           `db:"tags" json:"tags"`
	Status        string             `db:"status" json:"status"`
	LastHeartbeat pgtype.Timestamptz `db:"last_heartbeat" json:"last_heartbeat"`
	RegisteredAt  pgtype.Timestamptz `db:"registered_at" json:"registered_at"`
	CurrentTaskID uuid.UUID          `db:"current_task_id" json:"current_task_id"`
}

// current_task_id is the most recent non-terminal task assigned to this worker.
func (q *Queries) ListWorkers(ctx context.Context) ([]ListWorkersRow, error) {
	rows, err := q.db.Query(ctx, listWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkersRow
	for rows.Next() {
		var i ListWorkersRow
		if err := rows.Scan(
			&i.ID,
			&i.Tags,
			&i.Status,
			&i.LastHeartbeat,
			&i.RegisteredAt,
			&i.CurrentTaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerWorker = `-- name: RegisterWorker :one

INSERT INTO workers (id, tags, status, last_heartbeat, registered_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
    SET tags           = EXCLUDED.tags,
        status         = EXCLUDED.status,
        last_heartbeat = EXCLUDED.last_heartbeat
RETURNING id, tags, status, last_heartbeat, registered_at
`

type RegisterWorkerParams struct {
	ID            string             `db:"id" json:"id"`
	Tags          []string           `db:"tags" json:"tags"`
	Status        string             `db:"status" json:"status"`
	LastHeartbeat pgtype.Timestamptz `db:"last_heartbeat" json:"last_heartbeat"`
	RegisteredAt  pgtype.Timestamptz `db:"registered_at" json:"registered_at"`
}

// sqlc query file: workers table
// Generates Go code in internal/db/sqlc/ via `sqlc generate`
// See: ADR-008, TASK-002, TASK-006
func (q *Queries) RegisterWorker(ctx context.Context, arg RegisterWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, registerWorker,
		arg.ID,
		arg.Tags,
		arg.Status,
		arg.LastHeartbeat,
		arg.RegisteredAt,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Tags,
		&i.Status,
		&i.LastHeartbeat,
		&i.RegisteredAt,
	)
	return i, err
}

const updateWorkerStatus = `-- name: UpdateWorkerStatus :exec
UPDATE workers
SET status         = $2,
    last_heartbeat = NOW()
WHERE id = $1
`

type UpdateWorkerStatusParams struct {
	ID     string `db:"id" json:"id"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) UpdateWorkerStatus(ctx context.Context, arg UpdateWorkerStatusParams) error {
	_, err := q.db.Exec(ctx, updateWorkerStatus, arg.ID, arg.Status)
	return err
}
