-- Migration 000002: Make tasks.pipeline_id nullable with ON DELETE SET NULL (up)
-- When a pipeline is deleted, historical tasks retain their row but pipeline_id
-- is set to NULL instead of being blocked by the FK (SQLSTATE 23503).
-- See: TASK-013 fix iteration 2

-- Drop the implicit FK constraint created by REFERENCES pipelines(id) in 000001.
-- The constraint name is generated by PostgreSQL as tasks_pipeline_id_fkey.
ALTER TABLE tasks DROP CONSTRAINT tasks_pipeline_id_fkey;

-- Allow NULL so existing rows can survive after the referenced pipeline is gone.
ALTER TABLE tasks ALTER COLUMN pipeline_id DROP NOT NULL;

-- Re-create the FK with ON DELETE SET NULL: deleting a pipeline nullifies the
-- pipeline_id on all referencing tasks rather than blocking the DELETE.
ALTER TABLE tasks
    ADD CONSTRAINT tasks_pipeline_id_fkey
    FOREIGN KEY (pipeline_id) REFERENCES pipelines(id)
    ON DELETE SET NULL;
