// Package db manages the PostgreSQL connection pool and schema migration execution.
// Driver: pgx (native Go PostgreSQL driver, ADR-004).
// Query code: generated by sqlc from files in internal/db/queries/ (ADR-008).
// Migrations: managed by golang-migrate, embedded from internal/db/migrations/ (ADR-008).
// See: ADR-004, ADR-008, TASK-002
package db

import (
	"context"
	"embed"
	"errors"
	"fmt"

	"github.com/golang-migrate/migrate/v4"
	_ "github.com/golang-migrate/migrate/v4/database/pgx/v5" // pgx/v5 driver for golang-migrate
	"github.com/golang-migrate/migrate/v4/source/iofs"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Pool is the shared PostgreSQL connection pool type used across all services.
// Constructed by New and injected into repositories and query functions.
type Pool = pgxpool.Pool

//go:embed migrations/*.sql
var migrationsFS embed.FS

// New creates and validates a PostgreSQL connection pool from the given DSN.
// Also runs all pending up-migrations from the embedded migrations directory.
//
// Args:
//
//	ctx: Startup context; cancellation aborts the connection attempt.
//	dsn: PostgreSQL Data Source Name. Format: postgresql://user:password@host:port/dbname
//
// Returns:
//
//	A connected, migration-current pool ready for query use.
//	An error if the DSN is invalid, the database is unreachable, or any migration fails.
//
// Preconditions:
//   - The database user must have CREATE TABLE, ALTER TABLE, and INSERT privileges.
//   - The schema_migrations table may or may not exist; golang-migrate creates it.
//
// Postconditions:
//   - On success: the schema is at the latest migration version; the pool is open.
//   - On failure: any partially applied migration is rolled back before returning.
func New(ctx context.Context, dsn string) (*Pool, error) {
	if err := RunMigrations(dsn); err != nil {
		return nil, fmt.Errorf("db: migrations failed: %w", err)
	}

	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, fmt.Errorf("db: cannot open connection pool: %w", err)
	}

	// Verify connectivity with a lightweight query.
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("db: ping failed: %w", err)
	}

	return pool, nil
}

// RunMigrations applies all pending up-migrations from the embedded migrations directory.
// Idempotent: already-applied migrations are skipped.
// Called internally by New; exposed for use in test setup.
//
// Args:
//
//	dsn: The PostgreSQL connection string, used by golang-migrate directly.
//	     Must use the postgresql:// or postgres:// scheme.
//
// Postconditions:
//   - On success: schema is at the latest version.
//   - On "no change" (all migrations already applied): returns nil.
//   - On failure: error returned; schema is at the last successfully applied version.
func RunMigrations(dsn string) error {
	// golang-migrate's pgx/v5 driver requires the scheme to be "pgx5://".
	// Convert standard postgres:// or postgresql:// DSNs to the driver-specific scheme.
	pgx5DSN := toPgx5DSN(dsn)

	src, err := iofs.New(migrationsFS, "migrations")
	if err != nil {
		return fmt.Errorf("db: cannot load embedded migrations: %w", err)
	}

	m, err := migrate.NewWithSourceInstance("iofs", src, pgx5DSN)
	if err != nil {
		return fmt.Errorf("db: cannot initialize migrator: %w", err)
	}
	defer m.Close()

	if err := m.Up(); err != nil && !errors.Is(err, migrate.ErrNoChange) {
		return fmt.Errorf("db: migration up failed: %w", err)
	}

	return nil
}

// toPgx5DSN converts a standard postgres:// or postgresql:// DSN to the
// pgx5:// scheme required by the golang-migrate pgx/v5 database driver.
// If the DSN already uses pgx5://, it is returned unchanged.
//
// Args:
//
//	dsn: A PostgreSQL connection string, e.g. postgresql://user:pass@host/db
//
// Returns:
//
//	A connection string with the pgx5:// scheme.
func toPgx5DSN(dsn string) string {
	for _, prefix := range []string{"postgresql://", "postgres://"} {
		if len(dsn) >= len(prefix) && dsn[:len(prefix)] == prefix {
			return "pgx5://" + dsn[len(prefix):]
		}
	}
	return dsn
}
