// Package db manages the PostgreSQL connection pool and schema migration execution.
// Driver: pgx (native Go PostgreSQL driver, ADR-004).
// Query code: generated by sqlc from files in internal/db/queries/ (ADR-008).
// Migrations: managed by golang-migrate from files in internal/db/migrations/ (ADR-008).
// See: ADR-004, ADR-008, TASK-002
package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgxpool"
)

// Pool is the shared PostgreSQL connection pool type used across all services.
// Constructed by New and injected into repositories and query functions.
type Pool = pgxpool.Pool

// New creates and validates a PostgreSQL connection pool from the given DSN.
// Also runs pending up-migrations from internal/db/migrations/ on startup.
//
// Args:
//   ctx: Startup context; cancellation aborts the connection attempt.
//   dsn: PostgreSQL Data Source Name. Format: postgresql://user:password@host:port/dbname
//
// Returns:
//   A connected, migration-current pool ready for query use.
//   An error if the DSN is invalid, the database is unreachable, or any migration fails.
//
// Preconditions:
//   - The database user must have CREATE TABLE, ALTER TABLE, and INSERT privileges.
//   - The schema_migrations table may or may not exist; golang-migrate creates it.
//
// Postconditions:
//   - On success: the schema is at the latest migration version; the pool is open.
//   - On failure: any partially applied migration is rolled back before returning.
func New(ctx context.Context, dsn string) (*Pool, error) {
	// TODO: Implement in TASK-002
	panic("not implemented")
}

// RunMigrations applies all pending up-migrations from the embedded migrations directory.
// Idempotent: already-applied migrations are skipped.
// Called internally by New; exposed for use in test setup.
//
// Args:
//   dsn: The PostgreSQL connection string, used by golang-migrate directly.
//
// Postconditions:
//   - On success: schema is at the latest version.
//   - On failure: error returned; schema is at the last successfully applied version.
func RunMigrations(dsn string) error {
	// TODO: Implement in TASK-002
	panic("not implemented")
}
