// Package db — Repository interfaces for domain entities.
// These interfaces define the data access contracts consumed by API handlers,
// the Worker, and the Monitor. Implementations are generated by sqlc from
// internal/db/queries/ and wired in at startup.
// See: ADR-008, TASK-002
package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/nxlabs/nexusflow/internal/models"
)

// UserRepository provides read and write access to the users table.
// See: REQ-019, REQ-020, TASK-003, TASK-017
type UserRepository interface {
	// Create inserts a new User record. The PasswordHash must already be bcrypt-hashed.
	//
	// Args:
	//   ctx:  Request context.
	//   user: Populated User struct. ID must be a new UUID; CreatedAt is set by the database.
	//
	// Returns:
	//   The persisted User with database-populated fields (CreatedAt).
	//   An error if the username is already taken (unique constraint violation).
	Create(ctx context.Context, user *models.User) (*models.User, error)

	// GetByID retrieves a User by primary key.
	//
	// Returns nil, nil if no user with that ID exists.
	GetByID(ctx context.Context, id uuid.UUID) (*models.User, error)

	// GetByUsername retrieves a User by username for login credential checking.
	//
	// Returns nil, nil if no user with that username exists.
	GetByUsername(ctx context.Context, username string) (*models.User, error)

	// List returns all users. Admin-only operation.
	// See: REQ-020
	List(ctx context.Context) ([]*models.User, error)

	// Deactivate sets a User's active flag to false and, by contract,
	// triggers session invalidation for all of that user's active sessions.
	// The session invalidation is performed by the caller via SessionStore.DeleteAllForUser.
	//
	// Preconditions:
	//   - The user exists (caller verifies before calling).
	//   - Deactivation does not cancel in-flight Tasks (REQ-020 domain invariant).
	//
	// Postconditions:
	//   - On success: user.Active = false in the database.
	Deactivate(ctx context.Context, id uuid.UUID) error
}

// PipelineRepository provides CRUD access to the pipelines table.
// Ownership is enforced at the service layer, not here.
// See: REQ-022, TASK-013
type PipelineRepository interface {
	// Create inserts a new Pipeline. Returns the persisted record with ID and timestamps.
	Create(ctx context.Context, pipeline *models.Pipeline) (*models.Pipeline, error)

	// GetByID retrieves a Pipeline by primary key. Returns nil, nil if not found.
	GetByID(ctx context.Context, id uuid.UUID) (*models.Pipeline, error)

	// ListByUser returns all Pipelines owned by the given user.
	ListByUser(ctx context.Context, userID uuid.UUID) ([]*models.Pipeline, error)

	// List returns all Pipelines across all users. Admin-only at the service layer.
	List(ctx context.Context) ([]*models.Pipeline, error)

	// Update replaces the mutable fields of a Pipeline (name, phase configs, schema mappings).
	// Returns ErrNotFound if the pipeline does not exist.
	//
	// Preconditions:
	//   - Caller has verified ownership or admin role before calling.
	Update(ctx context.Context, pipeline *models.Pipeline) (*models.Pipeline, error)

	// Delete removes a Pipeline. Returns ErrActiveTasks if any non-terminal Task
	// references this pipeline (enforces the 409 contract from TASK-013).
	//
	// Preconditions:
	//   - Caller has verified ownership or admin role.
	//
	// Postconditions:
	//   - On success: pipeline is deleted; no tasks reference it.
	//   - On ErrActiveTasks: pipeline is not deleted; caller returns 409.
	Delete(ctx context.Context, id uuid.UUID) error

	// HasActiveTasks returns true if any non-terminal Task references this pipeline.
	// Used by Delete to enforce the 409 guard.
	HasActiveTasks(ctx context.Context, pipelineID uuid.UUID) (bool, error)
}

// TaskRepository provides read and write access to the tasks and task_state_log tables.
// State transitions must be validated against domain invariants before calling mutating methods.
// See: REQ-001, REQ-009, REQ-010, ADR-008, TASK-005, TASK-007
type TaskRepository interface {
	// Create inserts a new Task with status "submitted".
	// The caller transitions the status to "queued" via UpdateStatus after enqueuing.
	//
	// Args:
	//   ctx:  Request context.
	//   task: Populated Task struct. ID and ExecutionID must be set by the caller.
	Create(ctx context.Context, task *models.Task) (*models.Task, error)

	// GetByID retrieves a Task by primary key. Returns nil, nil if not found.
	GetByID(ctx context.Context, id uuid.UUID) (*models.Task, error)

	// ListByUser returns all Tasks submitted by the given user.
	// Satisfies Domain Invariant 5 (visibility isolation) at the query level.
	ListByUser(ctx context.Context, userID uuid.UUID) ([]*models.Task, error)

	// List returns all Tasks across all users. Admin-only at the service layer.
	List(ctx context.Context) ([]*models.Task, error)

	// UpdateStatus transitions a Task to a new status and records the transition in task_state_log.
	// The database trigger enforces valid (fromState, toState) pairs.
	//
	// Args:
	//   ctx:       Request context.
	//   id:        The Task to update.
	//   newStatus: The target state. Must be a valid forward transition from the current state.
	//   reason:    Human-readable reason stored in task_state_log.
	//   workerID:  Non-nil when transitioning to "assigned" or "running"; nil otherwise.
	//
	// Postconditions:
	//   - On success: task.Status = newStatus; task_state_log has a new entry.
	//   - On invalid transition: database trigger rejects and error is returned.
	UpdateStatus(ctx context.Context, id uuid.UUID, newStatus models.TaskStatus, reason string, workerID *string) error

	// IncrementRetryCount increments the retry_count for a Task.
	// Called by the Monitor on XCLAIM reclamation (ADR-002, TASK-009).
	IncrementRetryCount(ctx context.Context, id uuid.UUID) (int, error)

	// SetRetryAfterAndTags sets the retry_after timestamp and retry_tags on a Task atomically.
	// retry_after gates re-enqueue: when non-nil, the task is not dispatched until after that time.
	// retry_tags records which stream(s) the task must be re-enqueued to when the gate opens.
	// Called by the Monitor after XCLAIM to enforce backoff delay between retry attempts (TASK-010).
	//
	// Args:
	//   ctx:        Request context.
	//   id:         The Task to update.
	//   retryAfter: The earliest time the task may be re-enqueued. Nil clears the gate.
	//   retryTags:  The capability tag stream(s) to re-enqueue to. Empty clears stored tags.
	//
	// Postconditions:
	//   - On success: task.RetryAfter = retryAfter and task.RetryTags = retryTags in the database.
	SetRetryAfterAndTags(ctx context.Context, id uuid.UUID, retryAfter *time.Time, retryTags []string) error

	// ListRetryReady returns all Tasks in "queued" status whose retry_after has elapsed
	// (retry_after IS NOT NULL AND retry_after <= now()). Called by the Monitor scan loop
	// to find tasks that are ready to be re-enqueued to Redis after backoff delay (TASK-010).
	//
	// Returns an empty slice when no tasks are ready. Never returns nil.
	ListRetryReady(ctx context.Context) ([]*models.Task, error)

	// Cancel sets a Task's status to "cancelled".
	// Cancel authority: only the submitting User or an Admin may cancel (Domain Invariant 8).
	// Enforcement is at the service layer; this method does not check authority.
	//
	// Preconditions:
	//   - Task is in a cancellable state (submitted, queued, assigned, running).
	//   - Caller has verified cancel authority.
	Cancel(ctx context.Context, id uuid.UUID, reason string) error

	// GetStateLog returns all state transition log entries for a Task in chronological order.
	GetStateLog(ctx context.Context, taskID uuid.UUID) ([]*models.TaskStateLog, error)
}

// WorkerRepository provides read and write access to the workers table.
// See: REQ-004, REQ-016, ADR-002, TASK-006
type WorkerRepository interface {
	// Register inserts a new Worker record on startup.
	// Idempotent: if a Worker with the same ID already exists, its record is updated.
	//
	// Args:
	//   ctx:    Request context.
	//   worker: Worker struct with ID, Tags, Status="online", and RegisteredAt set.
	Register(ctx context.Context, worker *models.Worker) (*models.Worker, error)

	// GetByID retrieves a Worker by its string ID. Returns nil, nil if not found.
	GetByID(ctx context.Context, id string) (*models.Worker, error)

	// List returns all registered Workers with their current status.
	// Includes CurrentTaskID populated from a JOIN on the tasks table.
	List(ctx context.Context) ([]*models.Worker, error)

	// UpdateStatus sets a Worker's status and last_heartbeat timestamp.
	// Called by the Monitor when marking a worker down (ADR-002).
	UpdateStatus(ctx context.Context, id string, status models.WorkerStatus) error
}

// TaskLogRepository provides write access for log line persistence (cold storage).
// Hot log storage is via Redis Streams; this repository handles cold PostgreSQL storage.
// See: ADR-008, TASK-016
type TaskLogRepository interface {
	// BatchInsert inserts multiple log lines from Redis into PostgreSQL cold storage.
	// Called by the background log sync goroutine every 60 seconds (ADR-008).
	//
	// Args:
	//   ctx:  Request context.
	//   logs: Slice of TaskLog entries. Must not be empty.
	//
	// Postconditions:
	//   - On success: all provided log lines are persisted in task_logs (partitioned by week).
	BatchInsert(ctx context.Context, logs []*models.TaskLog) error

	// ListByTask returns cold-stored log lines for a task, ordered by timestamp.
	// Used for Last-Event-ID replay on SSE reconnection (ADR-007).
	//
	// Args:
	//   ctx:       Request context.
	//   taskID:    The task whose logs are queried.
	//   afterID:   If non-empty, only log lines with ID > afterID are returned (for replay).
	ListByTask(ctx context.Context, taskID uuid.UUID, afterID string) ([]*models.TaskLog, error)
}

// ChainRepository provides create and read access to the chains and chain_steps tables.
// Chains are strictly linear: each pipeline appears at most once per chain.
// The database enforces linearity via UNIQUE(chain_id, pipeline_id) and UNIQUE(chain_id, position).
// See: REQ-014, ADR-003, TASK-014
type ChainRepository interface {
	// Create inserts a new Chain and its steps in a single atomic operation.
	// PipelineIDs must have at least two entries (a chain of one is not meaningful).
	// Duplicate pipeline IDs within PipelineIDs are rejected before insertion.
	//
	// Args:
	//   ctx:   Request context.
	//   chain: Populated Chain struct with ID, Name, UserID, and PipelineIDs set.
	//          The position of each ID in the slice is its step position (0-based).
	//
	// Returns:
	//   The persisted Chain with database-populated timestamps.
	//   An error if the insertion fails.
	Create(ctx context.Context, chain *models.Chain) (*models.Chain, error)

	// GetByID retrieves a Chain by primary key including its ordered PipelineIDs.
	// Returns nil, nil if no chain with the given ID exists.
	GetByID(ctx context.Context, id uuid.UUID) (*models.Chain, error)

	// FindByPipeline returns the Chain that contains the given pipeline_id, or nil if none.
	// Used by the chain trigger to determine whether a completed task's pipeline is chained.
	//
	// Args:
	//   ctx:        Request context.
	//   pipelineID: The pipeline whose chain membership is being queried.
	//
	// Returns:
	//   The Chain containing pipelineID, or nil if the pipeline is not in any chain.
	FindByPipeline(ctx context.Context, pipelineID uuid.UUID) (*models.Chain, error)

	// GetNextPipeline returns the pipeline_id that immediately follows pipelineID in chainID.
	// Returns nil when pipelineID is the last step in the chain.
	//
	// Args:
	//   ctx:        Request context.
	//   chainID:    The chain to inspect.
	//   pipelineID: The current pipeline whose successor is sought.
	//
	// Returns:
	//   Pointer to the next pipeline UUID, or nil if pipelineID is the last step.
	GetNextPipeline(ctx context.Context, chainID uuid.UUID, pipelineID uuid.UUID) (*uuid.UUID, error)
}

// Sentinel errors returned by repository methods.
var (
	// ErrNotFound is returned when the requested entity does not exist.
	ErrNotFound = &repoError{"not found"}
	// ErrActiveTasks is returned by PipelineRepository.Delete when active tasks exist.
	ErrActiveTasks = &repoError{"pipeline has active tasks"}
	// ErrConflict is returned on unique constraint violations (e.g. duplicate username).
	ErrConflict = &repoError{"conflict"}
)

type repoError struct{ msg string }

func (e *repoError) Error() string { return e.msg }
